# Site settings
title: Mrs.Kat
description: "Личный блог, где я делюсь своими мыслями, впечатлениями и идеями."
keywords: "блог, жизнь, америка, рептилии, игуана"
url: "http://mrskat.com"
twitter_username: me0wth
github_username:  me0wth66
instagram_username: me0wth66
encoding: utf-8
baseurl: '' # does not include hostname

# Build settings
markdown: kramdown
permalink: '/posts/:title/'

# Pagination
paginate: 5
paginate_path: "/blog/:num"

# Files for news section
collections:
  news:
    lebel: "Обновления"
    type: "posts"


# Static main pages
include: ['_pages']

# Pages plagin
#pages: ./_static_pages

# Excerpt
excerpt_separator: "<!-- cut -->"

# Emoji smile support
gems:
#  - jemoji
  - jekyll-paginate