# Site settings
title: Mrs.Kat
description: "Персональный сайт/блог/дневник/исповедальня, называйте его как хотите. Для меня это место, где я делюсь своими мыслями, впечатлениями и идеями."
url: "http://mrskat.com"
twitter_username: me0wth
github_username:  me0wth66
instagram_username: me0wth66
encoding: utf-8

# Build settings
markdown: kramdown
permalink: '/posts/:title/'

# Pagination
paginate: 3
paginate_path: "/page/:num"

# Category lists pages
collections:
  category-pages:
    output: true
    permalink: /category/:path/

# Static main pages
include: ['_pages']
relative_permalinks: false

# Pages plagin
pages: ./_static_pages

# Excerpt
excerpt_separator: "<!-- cut -->"

# Emoji
gems:
  - jemoji
