# Site settings
title: Mrs.Kat
description: "Личный блог, где я делюсь своими мыслями, впечатлениями и идеями."
keywords: "блог, жизнь, америка, рептилии, игуана"
url: "http://mrskat.com"
twitter_username: me0wth
github_username:  me0wth66
instagram_username: me0wth66
encoding: utf-8
baseurl: '' # does not include hostname

# Build settings
markdown: kramdown
permalink: '/posts/:title/'

#related posts
lsi:         false

# Pagination
paginate: 5
paginate_path: "/page/:num"

# Category lists pages
collections:
  category:
    output: true
    permalink: /category/:path/

# Static main pages
include: ['_pages']
relative_permalinks: false

# Pages plagin
#pages: ./_static_pages

# Excerpt
excerpt_separator: "<!-- cut -->"

# Emoji
gems:
  - jemoji
