# Site settings
title: MrsKat
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://mrskat.com"
twitter_username: me0wth
github_username:  me0wth66
encoding: utf-8

# Build settings
markdown: kramdown
permalink: '/posts/:title/'

# Pagination
paginate: 3
paginate_path: "/page/:num"

# Category lists pages
collections:
  category-pages:
    output: true
    permalink: /category/:path/

# Static main pages
include: ['_pages']
relative_permalinks: false

# Pages plagin
pages: ./_static_pages

# Excerpt
excerpt_separator: "<!-- cut -->"

# Emoji
gems:
  - jemoji
